01-DataStructure/sunny/1911_흙길보수하기.java
01-DataStructure/sunny/1927_최소힙.java
01-DataStructure/sunny/2075_N번째큰수.java
01-DataStructure/sunny/2493_탑.java
01-DataStructure/sunny/2800_괄호제거.java
01-DataStructure/sunny/3986_좋은단어.java

1. [2800번: 괄호 제거](https://www.acmicpc.net/problem/2800) [풀이 링크](https://mellow-shadow-fed.notion.site/2800-41b5891e618b4cee93acc2b594100f16?pvs=4) 
2. [2493번: 탑](https://www.acmicpc.net/problem/2493) [풀이 링크](https://mellow-shadow-fed.notion.site/2493-b772cb717a514b74a48ac1043f42e649?pvs=4)
3. [2075번: N번째 큰 수](https://www.acmicpc.net/problem/2075) [풀이 링크](https://mellow-shadow-fed.notion.site/2075-N-07ca883d1a484b409e016fbad811cce9?pvs=4)
4. [1927번: 최소 힙](https://www.acmicpc.net/problem/1927) [풀이 링크](https://mellow-shadow-fed.notion.site/1927-8d5bf438a2374782982b485f0623f4b3?pvs=4)
5. [3986번: 좋은 단어](https://www.acmicpc.net/problem/3986) [풀이 링크](https://mellow-shadow-fed.notion.site/3986-72c7d524701c4a1eb679b393e56294b5?pvs=4)
✨ 선택 문제  ✨
[1911번: 흙길 …

[Week 1] DataStructure - 선희

---

01-DataStructure/uijeong/1927_최소 힙.cpp
01-DataStructure/uijeong/2075_N번째 큰 수.cpp
01-DataStructure/uijeong/2493_탑.cpp
01-DataStructure/uijeong/2800_괄호제거.cpp
01-DataStructure/uijeong/3986_좋은단어.cpp

Partial Closes #1 
[2800](https://weak-meteoroid-883.notion.site/2800-dd25282e0bef4370aebff14f6fe8e2aa?pvs=4) 괄호제거
[2493](https://weak-meteoroid-883.notion.site/2493-0ed42b68d66b4e15b79842d114da5691?pvs=4) 탑
[2075](https://weak-meteoroid-883.notion.site/2075-N-159a0657c0424ecb8238883272aa4067?pvs=4) N번째 큰 수
[1927](https://weak-meteoroid-883.notion.site/1927-4b6ac1b405cd4b22bcf4dfc8dfcd88e2?pvs=4) 최소 힙
[3986](https://weak-meteoroid-883.notion.site/3986-8d005cb031024acd8cf6a7a16c0149f1?pvs=4) 좋은 단어

[Week 1] DataStructure - 의정

---

01-DataStructure/haeun/2075_N번째 큰 수.cpp
02-BruteForce/haeun/1025_제곱수 찾기.cpp
02-BruteForce/haeun/15686_치킨 배달.cpp
02-BruteForce/haeun/16937_두 스티커.cpp
02-BruteForce/haeun/22864_피로도.cpp
02-BruteForce/haeun/2798_블랙잭.md

- https://velog.io/@jxlhe46/백준-2798번.-블랙잭
- https://velog.io/@jxlhe46/백준-16937번.-두-스티커
- https://velog.io/@jxlhe46/백준-15686번.-치킨-배달
- https://velog.io/@jxlhe46/백준-1025번.-제곱수-찾기 (지각 제출)

[Week 2] BruteForce - 하은 

---

03-BackTracking/sunny/1182_부분수열의합.java
03-BackTracking/sunny/14888_연산자끼워넣기.java
03-BackTracking/sunny/16987_계란으로계란치기.java
03-BackTracking/sunny/2580_스도쿠.java
03-BackTracking/sunny/9663_N_Queen.java

[Week 3] 재귀 & 백트래킹 - 선희

---

03-BackTracking/haeun/1182_부분수열의 합.md
03-BackTracking/haeun/14888_연산자 끼워넣기.cpp
03-BackTracking/haeun/16987_계란으로 계란치기.cpp
03-BackTracking/haeun/2580_스도쿠.cpp
03-BackTracking/haeun/9663_N-Queen.cpp

- https://velog.io/@jxlhe46/백준-1182번.-부분수열의-합
- https://velog.io/@jxlhe46/백준-14888번.-연산자-끼워넣기
- https://velog.io/@jxlhe46/백준-9663번.-N-Queen
- https://velog.io/@jxlhe46/백준-2580번.-스도쿠
- https://velog.io/@jxlhe46/백준-16987번.-계란으로-계란치기
- 휴우~ 드뎌 지각 제출 아니다!! 🙄

[Week3] 재귀 & 백트래킹 - 하은

---

03-BackTracking/UiJeong/1182_부분 수열의 합.cpp
03-BackTracking/UiJeong/14888_연산자 끼워넣기.cpp
03-BackTracking/UiJeong/16987_계란으로 계란치기.cpp
03-BackTracking/UiJeong/2580_스도쿠.cpp
03-BackTracking/UiJeong/9663_N-Queen.cpp

[Week3] 재귀 & 백트래킹 - 의정

---

04-Divide-Conquer-Sorting/uijeong/1083_소트.cpp
04-Divide-Conquer-Sorting/uijeong/11728_배열합치기.cpp
04-Divide-Conquer-Sorting/uijeong/18870_좌표 압축.cpp
04-Divide-Conquer-Sorting/uijeong/1992_쿼드트리.cpp
04-Divide-Conquer-Sorting/uijeong/2447_별찍기10.cpp

closes #17 
[배열합치기](https://weak-meteoroid-883.notion.site/11728-fc53f7892c1b4f9e8e5b6678aada61c0?pvs=4)
[쿼드 트리](https://weak-meteoroid-883.notion.site/23fc942df36b48a892aec122dd0984f5?pvs=4)
[좌표 압축](https://weak-meteoroid-883.notion.site/142c855f68f24c38ac985997ea8c0b0a?pvs=4)
[별찍기10](https://weak-meteoroid-883.notion.site/10-43c6ba5aab754675a265cb40ae7f8954?pvs=4)
[소트](https://weak-meteoroid-883.notion.site/a1af724e95084fe9911c11a5ec2bf6b3?pvs=4)

[Week4] 분할정복 & 정렬 - 의정

---

05-BinarySearch/sunny/1654_랜선자르기.java
05-BinarySearch/sunny/2110_공유기설치.java
05-BinarySearch/sunny/2512_예산.java
05-BinarySearch/sunny/디펜스게임.java
05-BinarySearch/sunny/입국심사.java

[5주차] 이분탐색 & 파라메트릭 서치 - 선희

---

.vscode/settings.json
05-BinarySearch/haeun/1654_랜선 자르기.cpp
05-BinarySearch/haeun/2110_공유기 설치.cpp
05-BinarySearch/haeun/2512_예산.cpp
05-BinarySearch/haeun/2805_나무 자르기.cpp
05-BinarySearch/haeun/디펜스 게임.cpp
05-BinarySearch/haeun/입국심사.cpp

- https://velog.io/@jxlhe46/백준-1654번.-랜선-자르기
- https://velog.io/@jxlhe46/백준-2512번.-예산
- https://velog.io/@jxlhe46/백준-3079번.-입국심사
- https://velog.io/@jxlhe46/프로그래머스-디펜스-게임
- https://velog.io/@jxlhe46/백준-2110번.-공유기-설치

[Week5] 이분탐색 & 파라메트릭 서치 - 하은 

---

05-BinarySearch/uijeong/1654_랜선 자르기.cpp
05-BinarySearch/uijeong/2110_공유기 설치.cpp
05-BinarySearch/uijeong/2512_예산.cpp
05-BinarySearch/uijeong/Level3_디펜스게임.cpp
05-BinarySearch/uijeong/Level3_입국심사.cpp

#24 
[코테 스터디 정리본](https://www.notion.so/d22bb10171f24e5bba29bade3fb635e6?pvs=4)

[Week5] 이분탐색 & 파라메트릭 서치 - 의정

---

06-Greedy/sunny/11399_ATM.java
06-Greedy/sunny/11501_주식.java
06-Greedy/sunny/1477_휴게소세우기.java
06-Greedy/sunny/1931_회의실배정.java
06-Greedy/sunny/2141_우체국.java

[Week 6] 그리디 - 선희

---

06-Greedy/haeun/11399_ATM.cpp
06-Greedy/haeun/11501_주식.cpp
06-Greedy/haeun/1477_휴게소 세우기.cpp
06-Greedy/haeun/1931_회의실 배정.cpp
06-Greedy/haeun/2141_우체국.cpp

- https://velog.io/@jxlhe46/백준-2141번.-우체국
- https://velog.io/@jxlhe46/백준-1931번.-회의실-배정
- https://velog.io/@jxlhe46/백준-11501번.-주식

[Week6] 그리디 - 하은 

---

06-Greedy/uijeong/11399_ATM.cpp
06-Greedy/uijeong/11501_주식.cpp
06-Greedy/uijeong/1931_회의실 배정.cpp
06-Greedy/uijeong/2141_우체국.cpp
06-Greedy/uijeong/2258_정육점.cpp

[문풀](https://www.notion.so/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week6] 그리디 - 의정 

---

07-DP/haeun/11053_가장 긴 증가하는 부분 수열.cpp
07-DP/haeun/12865_평범한 배낭.cpp
07-DP/haeun/2579_계단 오르기.cpp
07-DP/haeun/N으로 표현.cpp
07-DP/haeun/정수 삼각형.cpp

- https://velog.io/@jxlhe46/백준-11053번.-가장-긴-증가하는-부분-수열
- https://velog.io/@jxlhe46/백준-2579번.-계단-오르기
- https://velog.io/@jxlhe46/알고리즘-배낭-문제-Knapsack-Problem
- https://velog.io/@jxlhe46/프로그래머스-N으로-표현
DP,,,, 넘모 어렵다,,,, 😱😱

[Week 7] DP - 하은

---

07-DP/sunny/12865_평범한배낭.java
07-DP/sunny/2579_계단오르기.java
07-DP/sunny/N으로표현.java
07-DP/sunny/정수삼각형.java

[Week 7] DP - 선희

---

07-DP/uijeong/11053_가장 긴 증가하는 부분 수열.cpp
07-DP/uijeong/12865_평범한 배낭.cpp
07-DP/uijeong/2579_계단오르기.cpp
07-DP/uijeong/Lv3_N으로 표현.cpp
07-DP/uijeong/Lv3_정수 삼각형.cpp

[기록](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week 7] DP - 의정

---

08-Graph-DFS-BFS/sunny/1389_케빈베이컨의6단계법칙.java
08-Graph-DFS-BFS/sunny/14502_연구소.java
08-Graph-DFS-BFS/sunny/16236_아기상어.java
08-Graph-DFS-BFS/sunny/16928_뱀과사다리게임.java
08-Graph-DFS-BFS/sunny/2206_벽부수고이동하기.java

[Week 8] 그래프 & BFS/DFS - 선희

---

08-Graph-DFS-BFS/uijeong/13898_케빈 베이컨의 6단계 법칙.cpp
08-Graph-DFS-BFS/uijeong/14502_연구소.cpp
08-Graph-DFS-BFS/uijeong/16236_아기상어.cpp
08-Graph-DFS-BFS/uijeong/16928_뱀과 사다리 게임.cpp
08-Graph-DFS-BFS/uijeong/2206_벽 부수고 이동하기.cpp

[풀이](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week 8] 그래프 & BFS/DFS - 의정

---

09-ShortestPath/sunny/10159_저울.java
09-ShortestPath/sunny/10282_해킹.java
09-ShortestPath/sunny/11403_경로찾기.java
09-ShortestPath/sunny/11404_플로이드.java
09-ShortestPath/sunny/1916_최소비용구하기.java

[Week9] 최단 경로 - 선희

---

09-ShortestPath/haeun/10159_저울.md
09-ShortestPath/haeun/10282_해킹.cpp
09-ShortestPath/haeun/11403_경로 찾기.cpp
09-ShortestPath/haeun/11404_플로이드.cpp
09-ShortestPath/haeun/1916_최소 비용 구하기.cpp

- https://velog.io/@jxlhe46/백준-10159번.-저울
- https://velog.io/@jxlhe46/그리디-다익스트라-알고리즘
- https://velog.io/@jxlhe46/DP-플로이드-워셜-알고리즘

[Week9] 최단 경로 - 하은 

---

09-ShortestPath/uijeong/10159_저울.cpp
09-ShortestPath/uijeong/10282_해킹.cpp
09-ShortestPath/uijeong/11403_경로찾기.cpp
09-ShortestPath/uijeong/11404_플로이드.cpp
09-ShortestPath/uijeong/1916.최소비용 구하기.cpp

[기록](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week9] 최단 경로 - 의정

---

10-MST/haeun/13418_학교 탐방하기.cpp
10-MST/haeun/16398_행성 연결.cpp
10-MST/haeun/1647_도시 분할 계획.cpp
10-MST/haeun/1717_집합의 표현.cpp
10-MST/haeun/1976_여행 가자.md

- https://velog.io/@jxlhe46/백준-1717번.-집합의-표현
- https://velog.io/@jxlhe46/백준-1976번.-여행가자
- https://velog.io/@jxlhe46/백준-1647번.-도시-분할-계획
- https://velog.io/@jxlhe46/백준-13418번.-학교-탐방하기

[Week10] 서로소 집합 + MST - 하은 

---

10-MST/sunny/13418_학교탐방하기.java
10-MST/sunny/16398_행성연결.java
10-MST/sunny/1647_도시분할계획.java
10-MST/sunny/1717_집합의표현.java
10-MST/sunny/1976_여행가자.java

[Week10] 서로소 집합 + MST - 선희

---

10-MST/uijeong/13418_학교 탐방하기.cpp
10-MST/uijeong/16398_행성 연결.cpp
10-MST/uijeong/1647_도시 분할 계획.cpp
10-MST/uijeong/1717_집합의 표현.cpp
10-MST/uijeong/1976_여행 가자.cpp

[문풀 노트](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week10] 서로소 집합 + MST - 의정

---

11-Implementation/uijeong/11559_뿌요뿌요.cpp
11-Implementation/uijeong/14499_주사위 굴리기.cpp
11-Implementation/uijeong/15683_감시.cpp
11-Implementation/uijeong/18808_스티커 붙이기.cpp
11-Implementation/uijeong/3190_뱀.cpp

[문풀 노트](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e&pvs=4)

[Week11] 시뮬레이션 - 의정

---

11-Implementation/sunny/11559_뿌요뿌요.java
11-Implementation/sunny/14499_주사위굴리기.java
11-Implementation/sunny/15683_감시.java
11-Implementation/sunny/18808_스티커붙이기.java
11-Implementation/sunny/3190_뱀.java

[Week11] 시뮬레이션 - 선희

---

.gitignore
11-Implementation/haeun/11559_뿌요뿌요.cpp
11-Implementation/haeun/14499_주사위 굴리기.cpp
11-Implementation/haeun/15683_감시.cpp
11-Implementation/haeun/18808_스티커 붙이기.cpp
11-Implementation/haeun/3190_뱀.cpp

노트북 고장 이슈로,, 1문제 밖에 못 풀었습니다,, 
다다음주 스터디 전까지 남은 4문제 풀 건데, 이와 무관하게 기간 내 미제출 벌금 4천원 내겠습니다!

[Week11] 시뮬레이션 - 하은 

---

12-CodingTest/sunny/개인정보수집유효기간.java
12-CodingTest/sunny/두큐합같게만들기.java
12-CodingTest/sunny/등산코스정하기.java
12-CodingTest/sunny/미로탈출명령어.java
12-CodingTest/sunny/이모티콘할인행사.java

[12주차] 카카오 기출 문제 - 선희

---

12-CodingTest/uijeong/개인정보 수집 유효기간.cpp
12-CodingTest/uijeong/두 큐 합 같게 만들기.cpp
12-CodingTest/uijeong/등산코스 정하기.cpp
12-CodingTest/uijeong/미로탈출 명령어.cpp
12-CodingTest/uijeong/이모티콘 할인행사.cpp

[링크](https://weak-meteoroid-883.notion.site/48cdd4d1c5b94941943d4fcbdd1ede76?v=7843fec28c9b4dedab13cd2fec4cc09e)

[12주차] 카카오 기출문제 - 의정

---

week13/sunny/11051_이항계수2.java
week13/sunny/2470_두용액.java
week13/sunny/5557_1학년.java
week13/sunny/9252_LCS2.java
week13/sunny/징검다리건너기.java

[13주차] DP, 이분탐색 - 선희

---

week14/sunny/16234_인구이동.java
week14/sunny/17144_미세먼지안녕.java
week14/sunny/아이템줍기.java
week14/sunny/여행경로.java
week14/sunny/퍼즐조각채우기.java

close #69 
[아이템 줍기](https://mellow-shadow-fed.notion.site/b29d2876638d4a57b19546d1b5e6cf8d?pvs=4)
[여행 경로](https://mellow-shadow-fed.notion.site/c9ddec9a91bd43b687b30c38878d9dce?pvs=4)
[퍼즐 조각 채우기](https://mellow-shadow-fed.notion.site/397d2f5695944bd2b656ccf836063552?pvs=4)
[인구 이동](https://mellow-shadow-fed.notion.site/16234-e5044a3c09a14704888b963805500f5d?pvs=4)
[미세먼지 안녕!](https://mellow-shadow-fed.notion.site/17144-94ab7f26d997440083beeabba9e5fe84?pvs=4)

[14주차] BFS/DFS, 시뮬레이션 - 선희

---

week14/haeun/16234_인구이동.cpp
week14/haeun/아이템 줍기.cpp
week14/haeun/여행경로.cpp

- https://velog.io/@jxlhe46/프로그래머스-Lv3.-아이템-줍기
- https://velog.io/@jxlhe46/백준-16234번.-인구-이동
2문제 미제출이욤,,,,🥹🥹 시뮬레이션 문제는 항상 어렵네요,,,

[14주차] 그래프 탐색, 시뮬레이션 - 하은 

---

week15/haeun/16926_배열 돌리기1.cpp
week15/haeun/1715_카드 정렬하기.cpp
week15/haeun/2590_색종이.cpp
week15/haeun/가장 많이 받은 선물.cpp
week15/haeun/구명보트.cpp

- https://velog.io/@jxlhe46/프로그래머스-Lv1.-가장-많이-받은-선물
- https://velog.io/@jxlhe46/프로그래머스-Lv2.-구명보트
- https://velog.io/@jxlhe46/백준-16926번.-배열-돌리기-1
- https://velog.io/@jxlhe46/백준-2590번.-색종이

[15주차] 구현, 그리디 - 하은

---

week15/sunny/16926_배열돌리기1.java
week15/sunny/1715_카드정렬하기.java
week15/sunny/2590_색종이.java
week15/sunny/가장많이받은선물.java
week15/sunny/구명보트.java

[카카오: 가장 많이 받은 선물](https://mellow-shadow-fed.notion.site/5c4f8fffa9344aba86686e9c9d1c0fc3?pvs=4)
[프로그래머스: 구명보트](https://mellow-shadow-fed.notion.site/1d4dc4dadfd1455d9482b34489dd3257?pvs=4)
[백준 2590번: 색종이](https://mellow-shadow-fed.notion.site/2590-53d74b034d46411e91338f7bbd0578d0?pvs=4)
[백준 1715번: 카드 정렬하기](https://mellow-shadow-fed.notion.site/1715-e7323861a69d4d3eb4acf447b015156d?pvs=4)
[백준 16926번: 배열 돌리기 1](https://mellow-shadow-fed.notion.site/16926-1-4c94d496b42d4b0c9ea2bff3b2f8397c?pvs=4)

[15주차] 구현, 그리디 - 선희

---

week16/haeun/16197_두 동전.cpp
week16/haeun/2023_신기한 소수.cpp
week16/haeun/2583_영역 구하기.cpp
week16/haeun/도넛과 막대 그래프.cpp
week16/haeun/수식 최대화.cpp

- closed #78 
- https://velog.io/@jxlhe46/프로그래머스-Lv2.-도넛과-막대-그래프
- https://velog.io/@jxlhe46/프로그래머스-Lv2.-수식-최대화
- https://velog.io/@jxlhe46/백준-2023번.-신기한-소수
- https://velog.io/@jxlhe46/백준-16197번.-두-동전

[16주차] 랜덤 문제 - 하은 

---

week17/haeun/14501_퇴사.cpp
week17/haeun/2468_안전영역.cpp

- https://velog.io/@jxlhe46/백준-2468번.-안전-영역
- https://velog.io/@jxlhe46/백준-14501번.-퇴사
- 3문제 미제출이욤... 설연휴를 즐겼습니다 🙂

[17주차] 랜덤 문제 - 하은

---

week17/haeun/산 모양 타일링.cpp
week17/haeun/주사위 고르기.cpp
week17/haeun/택배 배달과 수거하기.cpp
week18/haeun/2661_좋은 수열.cpp
week18/haeun/주차 요금 계산.cpp

- https://velog.io/@jxlhe46/프로그래머스-Lv2.-주차-요금-계산
- https://velog.io/@jxlhe46/백준-2661번.-좋은-수열
- 3문제 미제출 입니닷,,,

[18주차] 랜덤 문제 - 하은 

---

week16/uijeong/Lv2_수식 최대화.cpp
week17/uijeong/14501_퇴사.cpp
week17/uijeong/2468_안전 영역.cpp

[17주차] 랜덤 문제 - 의정

---

week19/haeun/18430_무기 공학.cpp
week19/haeun/4781_사탕 가게.cpp

- closed #92
- https://velog.io/@jxlhe46/백준-18430번.-무기-공학
- https://velog.io/@jxlhe46/백준-4781번.-사탕-가게

[19주차] 랜덤 문제 - 하은 

---

week20/haeun/18513_샘터.cpp
week20/haeun/가장 먼 노드.cpp

- https://velog.io/@jxlhe46/프로그래머스-Lv2.-가장-먼-노드
- https://velog.io/@jxlhe46/백준-18513번.-샘터
- closed #94

[20주차] 랜덤 문제 - 하은 

---

week22/sunny/13422_도둑.java
week22/sunny/2176_합리적인이동경로.java
week22/sunny/자물쇠와열쇠.java

[22주차] 문제 제출 - 선희

---

week22/haeun/13422_도둑.cpp
week22/haeun/2176_합리적인 이동경로.cpp
week22/haeun/자물쇠와 열쇠.cpp

- https://velog.io/@jxlhe46/KAKAO-Lv3.-자물쇠와-열쇠
- https://velog.io/@jxlhe46/백준-2176번.-합리적인-이동경로
- https://velog.io/@jxlhe46/백준-13422번.-도둑

22주차 문제 제출 

---

Week22/uijeong/13422_도둑.cpp
Week22/uijeong/2176_합리적인 이동경로.cpp
Week22/uijeong/Lv3_자물쇠와 열쇠.cpp

[합리적인 이동경로](https://weak-meteoroid-883.notion.site/b8cdda2df186474689c70a2ef6148294?pvs=4)

[Week22] 랜덤문제 - 의정

---

week23/haeun/13413_오셀로 재배치.cpp
week23/haeun/5904_moo 게임.md

- closed #107 
- https://velog.io/@jxlhe46/백준-13413번.-오셀로-재배치
- https://velog.io/@jxlhe46/백준-5904번.-Moo-게임

23주차 문제 제출 

---

week23/yubin/13413_오셀로 재배치.java
week23/yubin/5904_moo 게임.java

23주차 문제 제출

---

week24/uijeong/1038_감소하는 수.cpp
week24/uijeong/8911_거북이.cpp
week24/uijeong/Lv2_괄호 변환.cpp

[Week24] 랜덤문제 

---

week24/haeun/1038_감소하는 수.cpp
week24/haeun/8911_거북이.cpp
week24/haeun/괄호변환.cpp

- https://velog.io/@jxlhe46/KAKAO-Lv2.-괄호-변환
- https://velog.io/@jxlhe46/백준-1038번.-감소하는-수

24주차 문제 제출 

---

week24/yubin/1038_감소하는수.java
week24/yubin/8911_거북이.java
week24/yubin/괄호변환.java

24주차 문제 제출

---

week25/haeun/억억단을 외우자.cpp
week25/haeun/주차 요금 계산.cpp
week25/haeun/피로도.cpp

- https://velog.io/@jxlhe46/프로그래머스-Lv3.-억억단을-외우자
- closed #116

25주차 문제 제출 

---

week26/haeun/14722_우유 도시.cpp
week26/haeun/21318_피아노 체조.cpp
week26/haeun/양과 늑대.cpp

- https://velog.io/@jxlhe46/KAKAO-Lv3.-양과-늑대
- https://velog.io/@jxlhe46/백준-21318번.-피아노-체조
- https://velog.io/@jxlhe46/백준-14722번.-우유-도시

26주차 문제 제출 

---

week26/sunny/14722_우유도시.java
week26/sunny/21318_피아노체조.java
week26/sunny/양과늑대.java

26주차 문제 제출

---

week27/haeun/거리두기 확인하기.cpp
week27/haeun/성격유형 검사하기.cpp
week27/haeun/숫자 문자열과 영단어.cpp

- closed #127 
- https://velog.io/@jxlhe46/KAKAO-Lv1.-숫자-문자열과-영단어
- https://velog.io/@jxlhe46/KAKAO-성격-유형-검사하기
- https://velog.io/@jxlhe46/KAKAO-Lv2.-거리두기-확인하기
- Lv1 문제도 간단해보이는데 생각보다 시간이 좀 걸리네요! 연습이 더 필요할 거 같습니다! 
- 구글링이 안 되는 코테도 있으니까,, 자주 사용되는 STL은 정확히 외워둬야 할 거 같아요 🥲

27주차 문제 제출 

---

week28/uijeong/1806_부분합.cpp
week28/uijeong/20922_겹치는 건 싫어.cpp
week28/uijeong/2343_기타레슨.cpp

아니 기타 레슨 질문이용요ㅗㅛ오오오오오오오오오오 
close #132

[Week28] 랜덤 문제 - 의정

---

week28/haeun/1806_부분합.cpp
week28/haeun/20922_겹치는 건 싫어.cpp
week28/haeun/2343_기타 레슨.cpp

- https://velog.io/@jxlhe46/백준-1806번.-부분합
- https://velog.io/@jxlhe46/백준-2343번.-기타-레슨
- https://velog.io/@jxlhe46/백준-20922번.-겹치는-건-싫어

28주차 문제 제출 

---

week29/10799_쇠막대기.cpp
week29/12764_싸지방에 간 준하.cpp
week29/17484_진우의 달 여행.cpp

- https://velog.io/@jxlhe46/백준-12764번.-싸지방에-간-준하
- https://velog.io/@jxlhe46/백준-17484번.-진우의-달-여행
- https://velog.io/@jxlhe46/백준-10799번.-쇠막대기

29주차 문제 제출 

---

week29/uijeong/10799_쇠막대기.cpp
week29/uijeong/12764_싸지방에 간 준하.cpp
week29/uijeong/17484_진우의 달 여행(Small).cpp

29주차 문제 제출

---

week30/uijeong/1174_줄어드는 수.cpp
week30/uijeong/20164_홀수 홀릭 호석.cpp
week30/uijeong/2688_줄어들지 않아.cpp

Week30 랜덤 문제 - 의정

---

week30/sunny/1174_줄어드는수.java
week30/sunny/20164_홀수홀릭호석.java
week30/sunny/2688_줄어들지않아.java

30주차 문제 제출

---

week31/11399_ATM.cpp
week31/1300_K번째수.cpp
week31/19598_최소 회의실 개수.cpp

- https://velog.io/@jxlhe46/백준-1300번.-K번째-수
- https://velog.io/@jxlhe46/백준-19598번.-최소-회의실-개수
- closed #147

31주차 문제 제출 

---

week32/1504_특정한 최단 경로.cpp
week32/1753_최단경로.cpp
week32/2344_거울.cpp

- https://velog.io/@jxlhe46/백준-1504번.-특정한-최단-경로
- https://velog.io/@jxlhe46/백준-2344번.-거울
- https://velog.io/@jxlhe46/그리디-다익스트라-알고리즘
- closed #150

32주차 문제 제출

---

week32/uijeong/1504_특정한 최단경로.cpp
week32/uijeong/1753_최단경로.cpp
week32/uijeong/2344_거울.cpp

[32주차] 랜덤문제 - 의정

---

week33/13908_비밀번호.cpp
week33/1613_역사.cpp
week33/19951_태상이의 훈련소 생활.cpp

- https://velog.io/@jxlhe46/백준-1613번.-역사
- https://velog.io/@jxlhe46/백준-13908번.-비밀번호
- https://velog.io/@jxlhe46/백준-19951번.-태상이의-훈련소-생활
- closed #152

33주차 문제 제출 

---

week36/sunny/2922_즐거운단어.java

close #164 
참고 풀이 : https://velog.io/@beberiche/BOJ-2922-%EC%A6%90%EA%B1%B0%EC%9A%B4-%EB%8B%A8%EC%96%B4

[36주차] 문제 풀이

---

week36/haeun/2922_즐거운 단어.cpp
week37/haeun/15558_점프 게임.cpp

- https://velog.io/@jxlhe46/백준-2922번.-즐거운-단어
- https://velog.io/@jxlhe46/백준-15558번.-점프-게임

36, 37주차 문제 풀이 
